### ISSUE TITLE
Support for Halo 3?

### ISSUE THREAD

**Issue by cynojien** [ELREVENGE/HaloMCCPCSaveTransferTool#2]
Halo 3 is now in flighting and I have manually extracted some of my old saves to find that they also work in MCC like Halo Reach.

Any chance you guys are still working on this project and do you have any plans on adding Halo 3?

Currently attempting to open a Halo 3 directory in the app returns 0 results after it searches all the archives.

**Comment by ELREVENGE** [comment]
There will be support for Halo 3 maps and gametypes. I will have to dig my 360 out of the disorganized boxes I packed when I moved. Once I find it I'll update this issue to let you know the progress of Halo 3 support. Hopefully screenshots are saved the same way as they are for Reach so those can be transferred too.

**Comment by ELREVENGE** [comment]
I've found and set up my 360. I'll probably start working on the code side of things on Sunday. I don't expect that part to take very long but I'll post updates here and mark the issue resolved once it's complete and compiled. Thank you for your patience.

**Comment by ELREVENGE** [comment]
I started work on Halo 3 support. I would expect an update to the software soon. I've finished the code end of things and just need to hook up the UI and export process. 
While I was at it I also tried transferring a film but they are going to be more complicated than maps, gametypes or screenshots.
Maps, gametypes and screenshots can be transferred with the same process as reach files though.

**Comment by ELREVENGE** [comment]
The latest release has added Halo 3 support for maps, gametypes and screenshots
