### ISSUE TITLE
Some Halo 3 maps just don't work

### ISSUE THREAD

**Issue by Chillstice** [ELREVENGE/HaloMCCPCSaveTransferTool#3]
This isn't exclusive to this script - exporting the map variants directly from a hard drive using Horizon yields the same result - but I was hoping to get some help with this. Also I don't really know who else to ask because this is such a niche thing.

Some Halo 3 .mvar files (when extracted from an old Xbox 360 HDD) and installed in the `Halo The Master Chief Collection\halo3\map_variants` folder just refuse to appear in-game. This seems to be random because it doesn't matter what combination of characters are in the filename or the file size. About half the old maps just don't work and idk why. 

Has anyone else run into this issue? Does anyone know a work-around? I really need Neverland Ranch to work so I can share this relic with the world. 

Here's where you can download the non-functioning .mvar: [https://s.chillstice.com/T3H0i](https://s.chillstice.com/T3H0i)

**Comment by ELREVENGE** [comment]
Looking into it. Is this your map? https://imgur.com/a/5W7wqm5
I put it on a USB and saved a new copy named "BROKEN" with my 360. I was able to load that up fine.
I wasn't able to see the original in the custom games lobby or forge. I tried renaming the map (the file name in windows and in the file itself since it spells the name it was saved as) and that didn't work.
I'll continue to look into the issue.

**Comment by Chillstice** [comment]
Maybe the map file is corrupted somehow? It's meant to be for Foundry and it's a crazy 3-dimensional maze. 
Somehow I managed to find a video of the map and gametype being played: https://youtu.be/7ZY13cpWa8k?t=374

**Comment by ELREVENGE** [comment]
I have the file on a USB again but correctly this time. I think I screwed something up when using horizon to replace the file last time. I'm trying again now.

**Comment by Chillstice** [comment]
Ah, yeah Horizon is a bit clunky. Thanks for helping me with this, it's strange and frustrating.

**Comment by ELREVENGE** [comment]
Okay I have it working after putting it on a USB then using horizon and resaving it on the 360. 
[Neverland.zip](https://github.com/ELREVENGE/HaloMCCPCSaveTransferTool/files/5009501/Neverland.zip)
![image](https://user-images.githubusercontent.com/2909708/89090459-ee309c00-d357-11ea-87a4-685b4555f182.png)
Looking into why it didn't work in the first place now.

**Comment by Chillstice** [comment]
Holy hell, it works for me too. Thanks this is awesome.

Did you just have to re-save the map? Some of these maps were last saved over a decade ago.

I can provide you with more original map files that worked/ didn't work if you need them.

**Comment by ELREVENGE** [comment]
The original file you sent seems to not show up with the built in directory. When I placed it into the temporary directory it seems to show up just fine. Try placing the files that don't work into the temporary directory and see if that solves your issue.
![screenshot](https://user-images.githubusercontent.com/2909708/89090805-1caf7680-d35a-11ea-8752-253787c1a3d4.jpg)

**Comment by Chillstice** [comment]
This works for the most part, but there are still a couple maps that just don't work, but they're random garbage ones so I'll cut my losses. Thanks for spending the time to figure this out. It might even be nice to put a note regarding this in the guide.

**Comment by ELREVENGE** [comment]
> Holy hell, it works for me too. Thanks this is awesome.
> 
> Did you just have to re-save the map? Some of these maps were last saved over a decade ago.
> 
> I can provide you with more original map files that worked/ didn't work if you need them.

I'd like to try to find out why they don't work. If you don't mind sending the maps that don't work I'll look more into it in case others have this issue.

**Comment by Chillstice** [comment]
ah ok, here's the ones that refuse to work: [https://s.chillstice.com/BhOv2](https://s.chillstice.com/BhOv2)
Keep in mind that I probably made these back in like 2008 and they're probably really dumb and or stupid.
