### ISSUE TITLE
Can't export selected files.

### ISSUE THREAD

**Issue by Baledx** [ELREVENGE/HaloMCCPCSaveTransferTool#6]
Yeah, I can't export files when I click on export it simply does nothing,I tried running it in admin,disabling security and more but it won't export selected files.

**Comment by ELREVENGE** [comment]
The UI broke a while ago you might be running into the same issue. What version of the software are you running and what game's files are you trying to export? 
I'll look into this ASAP.

**Comment by ELREVENGE** [comment]
I've patched the issue in the latest release. ([v2.0.0.3](https://github.com/ELREVENGE/HaloMCCPCSaveTransferTool/releases/tag/v2.0.0.3))
